sudo: required
os:
 - linux

services:
  - docker

before_install:
  - sudo apt-get install -y git
#  - wget ftp://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/5.30-69.0/interproscan-5.30-69.0-64-bit.tar.gz
#  - tar -xf interproscan-5.30-69.0-64-bit.tar.gz -C /interproscan
#  - git clone https://github.com/KohlbacherLab/MultiLoc2.git


jobs:
  include:
    - stage: build docker image
      script:
      - pwd
      - ls
      - docker build -t multiloc2 
