sudo: required
os:
 - linux

services:
  - docker

before_install:
#  - travis_wait 20 wget ftp://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/5.30-69.0/interproscan-5.30-69.0-64-bit.tar.gz
  - wget -q ftp://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/5.30-69.0/interproscan-5.30-69.0-64-bit.tar.gz
  - tar -xf interproscan-5.30-69.0-64-bit.tar.gz
  - mv interproscan-5.30-69.0 /interproscan

jobs:
  include:
    - stage: build docker image
      script:
      - cd ..
      - docker build -t multiloc2 MultiLoc2/
      - docker run --rm -v /interproscan:/interproscan -e INTERPROSCAN=/interproscan multiloc2 ./run_multiloc2.sh test.fasta animal test.res
